// <auto-generated />
using System;
using FitBoard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitBoard.Api.Data.Migrations
{
    [DbContext(typeof(FitBoardDbContext))]
    [Migration("20260917025612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FitBoard.Api.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("主鍵");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("動作名稱，對應 CSV exercise_title，唯一，例如 Squat (Barbell)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Exercises", null, t =>
                        {
                            t.HasComment("動作目錄（跨訓練共用的動作主檔）");
                        });
                });

            modelBuilder.Entity("FitBoard.Api.Entities.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("主鍵");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT")
                        .HasComment("距離（公里），對應 CSV distance_km，有氧等用途，可為空");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasComment("持續秒數，對應 CSV duration_seconds，可為空");

                    b.Property<int?>("Reps")
                        .HasColumnType("INTEGER")
                        .HasComment("次數，對應 CSV reps，可為空");

                    b.Property<decimal?>("Rpe")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT")
                        .HasComment("自覺強度 RPE（約 1–10），對應 CSV rpe，可為空");

                    b.Property<int>("SetIndex")
                        .HasColumnType("INTEGER")
                        .HasComment("組序，對應 CSV set_index，同動作內從 0 起算");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("組類型，對應 CSV set_type：Warmup / Normal");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT")
                        .HasComment("重量（公斤），對應 CSV weight_kg，可為空");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("INTEGER")
                        .HasComment("所屬訓練動作 FK → WorkoutExercises.Id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "SetIndex")
                        .IsUnique();

                    b.ToTable("ExerciseSets", null, t =>
                        {
                            t.HasComment("組數明細（單一 WorkoutExercise 下的每一組）");
                        });
                });

            modelBuilder.Entity("FitBoard.Api.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("主鍵");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasComment("訓練備註，對應 CSV description，可為空");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT")
                        .HasComment("訓練結束時間，對應 CSV end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasComment("訓練開始時間，對應 CSV start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("訓練標題，對應 CSV title，例如 Upper、Arm/Shoulder");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("Workouts", null, t =>
                        {
                            t.HasComment("訓練紀錄（一次完整訓練 session）");
                        });
                });

            modelBuilder.Entity("FitBoard.Api.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("主鍵");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER")
                        .HasComment("動作主檔 FK → Exercises.Id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasComment("此動作在該次訓練的備註，對應 CSV exercise_notes，可為空");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasComment("此動作在該次訓練中的順序（由匯入順序或手動指定）");

                    b.Property<int?>("SupersetId")
                        .HasColumnType("INTEGER")
                        .HasComment("超組編號，對應 CSV superset_id；同組動作共用同一值，可為空");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER")
                        .HasComment("所屬訓練 FK → Workouts.Id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "SortOrder");

                    b.ToTable("WorkoutExercises", null, t =>
                        {
                            t.HasComment("單次訓練中的動作項目（Workout 與 Exercise 的中介）");
                        });
                });

            modelBuilder.Entity("FitBoard.Api.Entities.ExerciseSet", b =>
                {
                    b.HasOne("FitBoard.Api.Entities.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("FitBoard.Api.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("FitBoard.Api.Entities.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitBoard.Api.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitBoard.Api.Entities.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("FitBoard.Api.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitBoard.Api.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
